name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x'

    - name: Restore dependencies
      run: dotnet restore ./RedisClient/RedisClient/RedisClient.csproj

    - name: Build project
      run: dotnet build ./RedisClient/RedisClient/RedisClient.csproj --configuration Release --no-restore

    - name: Pack project
      run: dotnet pack ./RedisClient/RedisClient/RedisClient.csproj --configuration Release --no-build --output ./nupkg

    - name: Create NuGet.Config
      run: |
        dotnet new nugetconfig
        dotnet nuget add source https://nuget.pkg.github.com/renancp01/index.json -n github -u renancp01 -p ${{ secrets.TOKENREDIS }}

    - name: Publish to GitHub Packages
      run: dotnet nuget push ./nupkg/*.nupkg --source "github"
