name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/RedisClient/RedisClient.csproj

    - name: Build project
      run: dotnet build ./src/RedisClient/RedisClient.csproj --configuration Release --no-restore

    - name: Pack project
      run: dotnet pack ./src/RedisClient/RedisClient.csproj --configuration Release --no-build --output ./nupkg

    - name: Determine version
      id: version
      run: echo "::set-output name=version::$(date +%Y%m%d%H%M%S)"

    - name: Rename package with new version
      run: |
        for file in ./nupkg/*.nupkg; do
          base=$(basename $file .nupkg)
          newname="${base}-v${{ steps.version.outputs.version }}.nupkg"
          mv $file ./nupkg/$newname
        done

    - name: Create NuGet.Config
      run: |
        mkdir -p ~/.nuget/NuGet
        echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
        <configuration>
          <packageSources>
            <add key=\"github\" value=\"https://nuget.pkg.github.com/renancp01/index.json\" />
          </packageSources>
          <packageSourceCredentials>
            <github>
              <add key=\"Username\" value=\"renancp01\" />
              <add key=\"ClearTextPassword\" value=\"${{ secrets.TOKENREDIS }}\" />
            </github>
          </packageSourceCredentials>
        </configuration>" > ~/.nuget/NuGet/NuGet.Config

    - name: Publish to GitHub Packages
      run: dotnet nuget push ./nupkg/*.nupkg --source "github" --skip-duplicate